### PR TITLE
Add logo for HSGS Tran Dai Nghia - Ho Chi Minh City

### PR DESCRIPTION
**Pull request by trnthienphc2003**

### CODE REVIEW

**Comment by leduythuccs** [comment]
The logo is quite big, could you help reduce it to 100x100, or 60x60 would be nice

**Comment by vinhhien323** [comment]
#5 This is a 100-pixel version of this logo. Thank you.
https://drive.google.com/file/d/1lwwG9adz7Q3osF1X8zh1y7kgU3VfuVzW/view?usp=sharing

**Comment by DatDo1309** [comment]
Tôi đã fix về 100x100, add giúp tôi nhé


Vào Th 7, 7 thg 10, 2023 lúc 19:55 Hien ***@***.***> đã viết:

**Comment by DatDo1309** [comment]
https://drive.google.com/file/d/1wmZ4jb1K8J2RcFnmcjObNlXKHHb_RE0e/view?usp=drivesdk

Tôi đã resize ảnh và upload lên Google Drive. Vui lòng add logo trường giúp
tôi

Vào Th 7, 7 thg 10, 2023 lúc 19:55 Hien ***@***.***> đã viết:

**Comment by leduythuccs** [comment]
close beause of #6

**Pull request closed without merging**
